id: ID431B4D2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-02-21T13:31:08+00:00'
last_modified: '2022-06-09T17:47:37.257769+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD137889
  title: མཉམ་མེད་ཇོ་བོ་རྗེ་དཔལ་ལྡན་ཨ་ཏི་ཤའི་རྣམ་པར་ཐར་པ་ཕྱོགས་བསྡུས་དད་པའི་འཇུག་ངོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6248':
      image_group_id: I2PD18897
      title: Volume 1 of mnyam med jo bo rje dpal ldan a ti sha'i rnam par thar pa
        phyogs bsdus dad pa'i 'jug ngogs/
      total_pages: 188
      order: 1
      base_file: 6248.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
